const GET_CAMPAIGN_LIST = 'GET_CAMPAIGN_LIST'
const GET_CAMPAIGN_DETAIL = 'GET_CAMPAIGN_DETAIL'
const GET_POSITION_CAMPAIGN_RESULT = 'GET_POSITION_CAMPAIGN_RESULT'

export { GET_CAMPAIGN_LIST, GET_CAMPAIGN_DETAIL, GET_POSITION_CAMPAIGN_RESULT }
